spring:
  application:
    name=Spring in Action
  datasource:
    generate-unique-name=false
    name=tacoCloud
  thymeleaf:
    cache=false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR_GOOGLE_CLIENT_ID
            clientSecret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile