spring:
  data:
    rest:
      basePath: /data-api
  application:
    name: Spring in Action
  datasource:
    generate-unique-name: false
    name: tacoCloud
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 734467333558-s3m136cb0q6v5mhmt047d3aqg0bi5cvb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        security: DEBUG